# Generated by Django 4.2.1 on 2023-06-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_plan_userplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user_plan',
        ),
        migrations.AddField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='main.plan'),
            preserve_default=False,
        ),
    ]
